Finish gps support
atomgomba/orangebox pull request #9
Opened 2024-01-28 21:25 UTC by tblaha

To be able to generate identical output to bb-log-viewer also if GPS is included, I did the following:
- added a `last_gps_home_frame` variable to the `ctx` that is updated everytime GPS_HOME is parsed
- implement the predictors for GPS coordinates (latitude and longitude separately, which is caught explicitely in `reader.py`)
- ensured that only intra, slow and GPS fields are added to field_names (GPS home isn't written out by bb-log-viewer)
- add GPS data to the frame the same way slow frames have been
- updated `parser_test.py`. I ran 2 separate test cases through it, one with GPS and one without. However, more testing would be beneficial. @atomgomba would you still have some test `.csv` lying around?

2024-01-30 07:33 UTC, atomgomba commented
@tblaha Once again, thank you for your contribution, I really appreciate it! :) Please rebase this onto master

2024-01-30 09:59 UTC, tblaha commented
No problem!
I use this tool to read data into a pandas dataframe and do the fixed-point to floating-point unit conversions there. Would you be interested to add this, for instance as a `.to_pandas(convert_units=True)` method, or something similar?

2024-02-02 08:33 UTC, atomgomba commented
@tblaha Sorry for the delays, I have limited time, but I'm planning to test this today. If all goes well I'm going to push changes to the documentation, including README, and finally create a new PyPi release :)

2024-02-02 11:00 UTC, atomgomba requested changes
The decoded output looks correct, I have made some remarks on the code

2024-02-02 11:00 UTC, atomgomba commented on orangebox/predictors.py
> +    # TODO: store GPS frame history
This TODO comment is now obsolete, please remove it

2024-02-02 11:00 UTC, atomgomba commented on orangebox/predictors.py
> +    return ctx.last_gps_home_frame.data[0] + new if ctx.last_gps_home_frame.data else 0
Please put the second member of this addition in parentheses for readability and extract this long expression into a variable named `result`

2024-02-02 11:00 UTC, atomgomba commented on orangebox/predictors.py
> +    return ctx.last_gps_home_frame.data[0] + new if ctx.last_gps_home_frame.data else 0
This returns an `int`, please divide `result` by `10_000_000` so it becomes directly usable by consumers

2024-02-02 11:00 UTC, atomgomba commented on orangebox/predictors.py
> +    # TODO: store GPS frame history
Obsolete comment, please remove

2024-02-02 11:00 UTC, atomgomba commented on orangebox/predictors.py
> +    return ctx.last_gps_home_frame.data[1] + new if ctx.last_gps_home_frame.data else 0
Please extract this long expression as well and add parentheses

2024-02-02 11:00 UTC, atomgomba commented on orangebox/reader.py
> +                    if (field_defs[frame_type][i].name == "GPS_coord[1]") \
Please remove the parentheses, it's not required in Python

2024-02-02 11:00 UTC, atomgomba commented on orangebox/reader.py
> +                    if (field_defs[frame_type][i].name == "GPS_coord[1]") \
Please extract the expression `field_defs[frame_type][i].name` into a variable called `fdef_name` and do not wrap the condition

2024-02-02 11:00 UTC, atomgomba commented on orangebox/parser.py
> +        for ftype in [FrameType.INTRA, FrameType.SLOW, FrameType.GPS]:
Nice catch! :+1:

2024-02-02 11:00 UTC, atomgomba commented on orangebox/parser.py
> +            edata = []
Please give a more descriptive name to this variable, maybe `extra_data`?

2024-02-02 11:00 UTC, atomgomba commented on parser_test.py
> +        if (i < intra_inter_len):
No parentheses please

2024-02-02 11:00 UTC, atomgomba commented on parser_test.py
> +            curMaxLen = intra_inter_len
Please use `snake_case` naming (everywhere in this file)

2024-02-02 11:04 UTC, atomgomba commented on orangebox/predictors.py
> +    return ctx.last_gps_home_frame.data[1] + new if ctx.last_gps_home_frame.data else 0
Also divide the result by `10_000_000`

2024-02-02 11:30 UTC, atomgomba commented
I just realized just blindly dividing by `10_000_000` would mess with the altitude value, if my thinking is right. Feel free to disregard this part, we can fix this once this is merged is a separate PR

2024-02-04 13:53 UTC, tblaha commented
Thanks for the review, looks like I need to brush up on some PEP8! I addressed all your comments and ran the tests again.
I agree that processing variables (like converting units or converting fixed point to floating point) should probably be done in other methods. It's also not done by bb-log-viewer; it just dumps the raw values into the CSV for all other fields as well.

2024-02-04 16:04 UTC, atomgomba approved these changes

2024-02-04 16:04 UTC, merged

2024-02-04 16:05 UTC, atomgomba commented
@tblaha Good job, thank you! :partying_face: